// Generated by CoffeeScript 1.12.5
(function() {
  $(function() {
    return $('form').submit(function(event) {
      var data, url;
      event.preventDefault();
      url = $(this).attr('action');
      data = $(this).serialize();
      return $.post(url, data, function(response) {
        return $('#signup').html('<p>Thanks for signing up!</p>');
      }).fail(function(jqXHR) {
        return alert(jqXHR.status + " " + jqXHR.statusText);
      });
    });
  });


  /*
  $ ->
    $('form').submit (event) ->
      event.preventDefault()
  
      url = $(@).attr 'action'
      data = $(@).serialize()
  
      $.ajax url,
        data: data
        type: 'POST'
        success: (response) ->
          $('#signup').html '<p>Thanks for signing up!</p>'
   */

}).call(this);
